name: "{{ config_profile_name }}"
# Update with modified config (e.g., changed log level)
config:
  {
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "MainInbound",
        "port": 10000,
        "protocol": "shadowsocks",
        "settings": {
          "clients": [],
          "network": "tcp,udp"
        },
        "sniffing": {
          "enabled": true,
          "destOverride": ["http", "tls"]
        }
      }
    ],
    "outbounds": [
      {
        "tag": "DIRECT",
        "protocol": "freedom"
      }
    ],
    "routing": {
      "rules": []
    }
  }